### ISSUE TITLE
Does not compile on elixir 1.8-rc

### ISSUE THREAD

**Issue by lukaszsamson** [lexmag/oauther#14]
```
== Compilation error in file lib/oauther.ex ==
** (CompileError) lib/oauther.ex:185: invalid call Enum.unquote(split_with)(enum, fun)
    lib/oauther.ex:185: (module)
```

**Comment by lukaszsamson** [comment]
Looks lika a regression in 1.8 https://github.com/elixir-lang/elixir/issues/8588
